linters:
  presets:
    # found in: golangci-lint help linters
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    # - style  # turned off, can be too much
    - test
    - unused
  disable:
    - prealloc  # it's just a performance optimization
    - cyclop
    - funlen
    - gocognit
    - exhaustruct  # TODO? annoying for now
    - goerr113  # TODO enable later
    - godot

    # deprecated:
    - scopelint
    - maligned
    - exhaustivestruct
    - deadcode
    - varcheck

    # TODO disable because currently not available for go1.18
    - bodyclose
    - contextcheck
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - tparallel
    - unparam

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  govet:
    enable:
      - shadow
