# Make sure to check the documentation at https://goreleaser.com
version: 2 # Goreleaser v2

release:
  draft: true
  replace_existing_draft: true

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: linux
    main: ./cmd/tkey-verification
    binary: tkey-verification
    env:
      - GOPROXY=https://proxy.golang.org,direct
      - GOSUMDB=sum.golang.org
      - CGO_ENABLED=0

    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -buildvcs=false

    # Custom ldflags mostly to avoid setting main.date which for some
    # reason is default
    ldflags:
      -w -X main.version={{ .Version }} -buildid=

  - id: darwin
    main: ./cmd/tkey-verification
    binary: tkey-verification
    env:
      - GOPROXY=https://proxy.golang.org,direct
      - GOSUMDB=sum.golang.org
      - CGO_ENABLED=1

    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -buildvcs=false

    # Custom ldflags mostly to avoid setting main.date which for some
    # reason is default
    ldflags:
      -w -X main.version={{ .Version }} -buildid=

  - id: windows
    main: ./cmd/tkey-verification
    binary: tkey-verification
    env:
      - GOPROXY=https://proxy.golang.org,direct
      - GOSUMDB=sum.golang.org
      - CGO_ENABLED=0

    goos:
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
      - -buildvcs=false

    # Custom ldflags mostly to avoid setting main.date which for some
    # reason is default
    ldflags:
      -w -X main.version={{ .Version }} -buildid=

universal_binaries:
  - ids:
      - darwin
    replace: true
    name_template: "tkey-verification"
    hooks:
      post: gon gon.hcl

archives:
  - format: tar.gz
    allow_different_binary_count: true
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "all" }}universal
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      format: zip
    files:
      - src: doc/tkey-verification.1
        dst: man
        strip_parent: true

nfpms:
  - package_name: tkey-verification
    vendor: Tillitis AB
    homepage: https://tillitis.se/
    maintainer: Tillitis <hello@tillitis.se>
    description: |-
      A program to sign or verify the identity of a Tillitis TKey.
    license: "GPL-2.0-only"
    formats:
      - apk
      - deb
      - rpm
      - archlinux # Since: v1.13
    bindir: /usr/bin
    release: 1
    section: misc
    contents:
      - src: doc/tkey-verification.1
        dst: /usr/share/man/man1/tkey-verification.1
        file_info:
           mode: 0644
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

winget:
  - name: TKeyVerification
    publisher: Tillitis
    short_description: "A program to sign or verify the identity of a Tillitis TKey."
    license: "GPL-2.0-only"
    publisher_url: https://tillitis.se/
    publisher_support_url: "https://github.com/tillitis/tkey-verification/issues/new"
    package_identifier: Tillitis.TKeyVerification
    homepage: "https://tillitis.se/"
    description: "A program to sign or verify the identity of a Tillitis TKey."
    license_url: "https://github.com/tillitis/tkey-verification/blob/main/LICENSE"
    copyright: "Tillitis AB"
    skip_upload: true
    release_notes: "{{.Changelog}}"

    repository:
      owner: tillitis
      name: winget-pkgs

brews:
  - name: tkey-verification
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    directory: Formula
    # Caveats for the user of your binary.
    #caveats: "How to use this binary"
    homepage: "https://tillitis.se/"
    description: "A program to sign or verify the identity of a Tillitis TKey."
    license: "GPL-2.0-only"
    skip_upload: true
    install: |
      bin.install "tkey-verification"
      man1.install "man/tkey-verification.1"
    # Repository to push the generated files to.
    repository:
      owner: tillitis
      name: homebrew-tkey
      branch: main
      pull_request:
        enabled: true
        draft: true

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort:
  filters:
    exclude:
      - '^docs:'
      - '^test:'

