#!/bin/sh -eu

tag="${1?pass a verisigner-tag to build from (tkey-verification repo)}"
appsrepotag="${2?pass the tag in tillitis-key1-apps repo to use}"

if [ ! -e /.dockerenv ] && [ "${container:-}" != "podman" ]; then
  printf "expected to be run in container\n"
  exit 1
fi

# set -x

cd /
git clone https://github.com/tillitis/tillitis-key1-apps
cd tillitis-key1-apps
if [ -n "$(git branch -r --list "origin/$appsrepotag")" ]; then
  git checkout "$appsrepotag"
else
  git checkout -b "branch-$appsrepotag" "$appsrepotag"
fi
# git show --no-patch

cd /
git clone https://github.com/tillitis/tkey-verification
cd tkey-verification
if [ -n "$(git branch -r --list "origin/$tag")" ]; then
  git checkout "$tag"
else
  git checkout -b "branch-$tag" "$tag"
fi
# git show --no-patch

make -C apps verisigner/app.bin
