#!/bin/sh -e

if ! hash 2>/dev/null sha512sum; then
  sha512sum() {
    shasum -a 512 "$@"
  }
fi

version="$1"
if [ -z "$version" ]; then
  printf "give me a version number\n"
  exit 1
fi
shift

cd release-builds

any=
for file in *_"$version"_*; do
  [ -e "$file" ] || continue
  [ "${file##*.}" != "sha512" ] || continue
  hashf="$file.sha512"
  if [ -e "$hashf" ]; then
    printf "%s already exists, bailing out\n" "$hashf"
    exit 1
  fi
  sha512sum >"$hashf" "$file"
  printf "wrote %s\n" "$hashf"
  any=any
done

if [ -z "$any" ]; then
  printf "no binaries in release-builds/ with that version?\n"
fi
