# SPDX-FileCopyrightText: 2024 Tillitis AB <tillitis.se>
# SPDX-License-Identifier: BSD-2-Clause
version = 1

[[annotations]]
path = ".github/workflows/*"
SPDX-FileCopyrightText = "2022 Tillitis AB <tillitis.se>"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
     ".clang-format",
     ".editorconfig",
     ".gitignore",
     ".golangci.yml",
     ".goreleaser.yaml",
     "Makefile",
     "README.md",
     "RELEASE.md",
     "certs/client.crt",
     "certs/client.csr",
     "certs/client.key",
     "certs/server.crt",
     "certs/server.csr",
     "certs/server.key",
     "certs/tillitis.crl",
     "certs/tillitis.crt",
     "certs/tillitis.key",
     "cmd/tkey-sigsum-submit/testdata/0001020304050607-subm-valid",
     "cmd/tkey-sigsum-submit/testdata/0001020304050607-ver-valid",
     "cmd/tkey-sigsum-submit/testdata/000102030400DEAD-subm-invalid-sig",
     "cmd/tkey-sigsum-submit/testdata/policy",
     "doc/implementation-notes.md",
     "doc/tkey-verification.1",
     "doc/tkey-verification.scd",
     "doc/tkey-verify.1",
     "doc/tkey-verify.scd",
     "doc/tkey-sigsum-submit.1",
     "doc/tkey-sigsum-submit.scd",
     "go.mod",
     "go.sum",
     "release-builds/tkey-verification_0.0.2_linux-amd64.sha512",
     "internal/appbins/bins/README.md",
     "internal/appbins/bins/signer-v1.0.1.bin",
     "internal/appbins/bins/signer-v1.0.1.bin.sha512",
     "internal/appbins/bins/verisigner-v0.0.3.bin",
     "internal/appbins/bins/verisigner-v0.0.3.bin.deps",
     "internal/appbins/bins/verisigner-v0.0.3.bin.sha512",
     "internal/ssh/README.md",
     "release-builds/tkey-verification_0.0.2_macos-amd64.sha512",
     "release-builds/tkey-verification_0.0.2_macos-arm64.sha512",
     "release-builds/tkey-verification_0.0.2_macos-universal.sha512",
     "release-builds/tkey-verification_0.0.2_windows-amd64.exe.sha512",
     "release-builds/tkey-verification_0.0.3_linux-amd64.sha512",
     "release-builds/tkey-verification_0.0.3_macos-amd64.sha512",
     "release-builds/tkey-verification_0.0.3_macos-arm64.sha512",
     "release-builds/tkey-verification_0.0.3_macos-universal.sha512",
     "release-builds/tkey-verification_0.0.3_windows-amd64.exe.sha512",
     "tkey-verification.yaml.example-remote-sign",
     "tkey-verification.yaml.example-serve-signer"
]
SPDX-FileCopyrightText = "2022 Tillitis AB <tillitis.se>"
SPDX-License-Identifier = "BSD-2-Clause"


[[annotations]]
path = [
     "internal/appbins/bins/signer-v1.0.1.bin",
     "internal/appbins/bins/verisigner-v0.0.3.bin",
]
SPDX-FileCopyrightText = "2022 Tillitis AB <tillitis.se>"
SPDX-License-Identifier = "GPL-2.0-only"

[[annotations]]
path = [
     "signing-procedure.svg",
]
SPDX-FileCopyrightText = "2025 Tillitis AB <tillitis.se>"
SPDX-License-Identifier = "CC-BY-SA-4.0"
